# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:        Black Magic Exploitation
subtitle:     CTF's, Exploits, and Black Magic
description:  ViviTurtle personal blog for Write-ups in CTFs and Programming
keywords:     CTF exploitation Web
language:     "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:      "" # the subpath of your site, e.g. /blog
url:          "https://viviturtle.github.io" # the base hostname & protocol for your site. Have a look at robots.txt as well!
#url:          "http://localhost:4000" 
permalink:    /blog/:categories/:title
cover:        /images/cover.png
about:        /images/about.png

#pagination
paginate:    6
paginate_path: "page:num"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate